"""Address field added

Revision ID: eee9540d1033
Revises: 667e97474c4f
Create Date: 2026-07-10 01:09:13.433672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'eee9540d1033'
down_revision: Union[str, Sequence[str], None] = '667e97474c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_device_tracking_device_id'), table_name='device_tracking')
    op.drop_index(op.f('ix_device_tracking_id'), table_name='device_tracking')
    op.drop_table('device_tracking')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=11), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('order_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('items_count', sa.INTEGER(), nullable=False),
    sa.Column('original_total_price', sa.INTEGER(), nullable=False),
    sa.Column('final_total_price', sa.INTEGER(), nullable=False),
    sa.Column('total_prepare_time', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('device_tracking',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=True),
    sa.Column('access_version', sa.INTEGER(), nullable=True),
    sa.Column('first_login_at', sa.DATETIME(), nullable=False),
    sa.Column('last_login_at', sa.DATETIME(), nullable=False),
    sa.Column('last_logout_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_device_tracking_id'), 'device_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_device_tracking_device_id'), 'device_tracking', ['device_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('order_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=6), nullable=True),
    sa.Column('start_at', sa.DATETIME(), nullable=True),
    sa.Column('end_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('discount_percent', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.VARCHAR(), nullable=False),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('likes', sqlite.JSON(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('prepare_time', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('order_id', sa.VARCHAR(), nullable=False),
    sa.Column('product_id', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price_at_time', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    # ### end Alembic commands ###
